version: '3.9'

services:
  mysql:
    container_name: miniwallet-mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_USER=miniwallet
      - MYSQL_PASSWORD=miniwallet
      - MYSQL_ROOT_PASSWORD=miniwallet
      - MYSQL_DATABASE=miniwallet
  miniwalletapp:
    container_name: miniwalletapp
    image: docker.io/bitnami/laravel:9
    restart: always
    ports:
      - '80:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=miniwallet
      - DB_PASSWORD=miniwallet
      - DB_DATABASE=miniwallet
    volumes:
      - './miniwallet:/app'
    depends_on:
      - mysql
  